{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "ea572577-225a-4add-90a5-815125d22298",
   "metadata": {},
   "outputs": [],
   "source": []
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "a720e70d-f858-49f2-a15c-6336acfc6c13",
   "metadata": {},
   "outputs": [],
   "source": [
    "import streamlit as st\n",
    "import pandas as pd\n",
    "import numpy as np\n",
    "import requests\n",
    "import itertools\n",
    "import json\n",
    "import xmltodict\n",
    "from datetime import datetime\n",
    "\n",
    "st.set_page_config(layout=\"wide\")\n",
    "st.title(\"🏗️ 1365 사정율 분석 도구\")\n",
    "st.markdown(\"공고번호를 입력하면 복수예가 조합, 낙찰하한율, 개찰결과를 분석해 드립니다.\")\n",
    "\n",
    "# 사용자 입력\n",
    "Gongo_Nm = st.text_input(\"🔍 공고번호를 입력하세요\", \"\")\n",
    "\n",
    "if st.button(\"분석 시작\") and Gongo_Nm:\n",
    "\n",
    "    with st.spinner(\"📊 데이터를 불러오는 중입니다...\"):\n",
    "        try:\n",
    "            headers = {'User-Agent': 'Mozilla/5.0'}\n",
    "            service_key = 'NXIL0ccBuaYTU1TvOY7wEfHJzR%2FqBRUCwoIIWHdw%2Bcfy3qy8tVEHktbZ5o95y8XqdW4GrQaj%2FSawwFq7gmkhfA%3D%3D'\n",
    "\n",
    "            # ▶ 복수예가 상세\n",
    "            url1 = f'http://apis.data.go.kr/1230000/as/ScsbidInfoService/getOpengResultListInfoCnstwkPreparPcDetail?inqryDiv=2&bidNtceNo={Gongo_Nm}&bidNtceOrd=00&pageNo=1&numOfRows=15&type=json&ServiceKey={service_key}'\n",
    "            df1 = pd.json_normalize(json.loads(requests.get(url1).text)['response']['body']['items'])\n",
    "            df1 = df1[['bssamt', 'bsisPlnprc']].astype('float')\n",
    "            df1['SA_rate'] = df1['bsisPlnprc'] / df1['bssamt'] * 100\n",
    "            base_price = df1.iloc[1]['bssamt']\n",
    "\n",
    "            # ▶ 조합 평균 계산\n",
    "            combs = itertools.combinations(df1['SA_rate'], 4)\n",
    "            rates = [np.mean(c) for c in combs]\n",
    "            df_rates = pd.DataFrame(rates, columns=['rate']).sort_values('rate').reset_index(drop=True)\n",
    "            df_rates['조합순번'] = range(1, len(df_rates)+1)\n",
    "\n",
    "            # ▶ 낙찰하한율 조회\n",
    "            url2 = f'http://apis.data.go.kr/1230000/ad/BidPublicInfoService/getBidPblancListInfoCnstwk?inqryDiv=2&bidNtceNo={Gongo_Nm}&pageNo=1&numOfRows=10&type=json&ServiceKey={service_key}'\n",
    "            df2 = pd.json_normalize(json.loads(requests.get(url2).text)['response']['body']['items'])\n",
    "            sucsfbidLwltRate = float(df2.loc[0, 'sucsfbidLwltRate'])\n",
    "\n",
    "            # ▶ A값 계산\n",
    "            url3 = f'http://apis.data.go.kr/1230000/ad/BidPublicInfoService/getBidPblancListInfoCnstwkBsisAmount?inqryDiv=2&bidNtceNo={Gongo_Nm}&pageNo=1&numOfRows=10&type=json&ServiceKey={service_key}'\n",
    "            df3 = pd.json_normalize(json.loads(requests.get(url3).text)['response']['body']['items'])\n",
    "            cost_cols = ['sftyMngcst','sftyChckMngcst','rtrfundNon','mrfnHealthInsrprm','npnInsrprm','odsnLngtrmrcprInsrprm','qltyMngcst']\n",
    "            A_value = df3[cost_cols].apply(pd.to_numeric).sum(axis=1).iloc[0]\n",
    "\n",
    "            # ▶ 개찰결과\n",
    "            url4 = f'http://apis.data.go.kr/1230000/as/ScsbidInfoService/getOpengResultListInfoOpengCompt?serviceKey={service_key}&pageNo=1&numOfRows=999&bidNtceNo={Gongo_Nm}'\n",
    "            response4 = requests.get(url4)\n",
    "            items = json.loads(json.dumps(xmltodict.parse(response4.text)))['response']['body']['items']['item']\n",
    "            df4 = pd.DataFrame(items)\n",
    "            df4['bidprcAmt'] = pd.to_numeric(df4['bidprcAmt'])\n",
    "            df4['rate'] = (((df4['bidprcAmt'] - A_value) * 100 / sucsfbidLwltRate) + A_value) * 100 / base_price\n",
    "            df4 = df4.drop_duplicates(['rate'])\n",
    "            df4 = df4[(df4['rate'] >= 98) & (df4['rate'] <= 102)].copy()\n",
    "            df4 = df4[['prcbdrNm', 'rate']].rename(columns={'prcbdrNm': '업체명'})\n",
    "\n",
    "            # ▶ 사정율 + 업체명 결합\n",
    "            df_combined = pd.concat([\n",
    "                df_rates[['rate', '조합순번']].rename(columns={'조합순번': '업체명'}),\n",
    "                df4.rename(columns={'업체명': '업체명'})\n",
    "            ], ignore_index=True).sort_values('rate').reset_index(drop=True)\n",
    "            df_combined['rate'] = round(df_combined['rate'], 5)\n",
    "\n",
    "            # ▶ 시각화: 1순위 업체 강조\n",
    "            st.subheader(\"📈 분석 결과\")\n",
    "            top_bidder = df4.sort_values('rate').iloc[0]['업체명']\n",
    "            df_combined['강조'] = df_combined['업체명'].apply(lambda x: '🟢 ' + x if x == top_bidder else x)\n",
    "\n",
    "            st.dataframe(df_combined[['rate', '강조']], use_container_width=True)\n",
    "\n",
    "            # ▶ 다운로드\n",
    "            now = datetime.now().strftime(\"%Y%m%d_%H%M%S\")\n",
    "            filename = f\"사정율분석_{Gongo_Nm}_{now}.xlsx\"\n",
    "            df_combined[['rate', '업체명']].to_excel(filename, index=False)\n",
    "            with open(filename, \"rb\") as f:\n",
    "                st.download_button(\"📥 결과 엑셀 다운로드\", f, file_name=filename)\n",
    "\n",
    "        except Exception as e:\n",
    "            st.error(f\"❌ 오류 발생: {e}\")\n"
   ]
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python [conda env:base] *",
   "language": "python",
   "name": "conda-base-py"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.12.7"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
